name: ${project.name}
version: ${project.version}
main: com.bermudalocket.lastseen.LastSeen
api-version: 1.13

commands:
  seen:
    description: Retrieve the date and time a player was last seen.
    usage: |

      §e/<command>§f - Retrieve the date and time a player was last seen.

  firstseen:
    description: Retrieve the date and time a player first logged in to the server.
    usage: |

      §e/<command>§f - Retrieve the date and time a player first logged in to the server.

  date:
    description: Show the current date and time in the server's time zone.
    usage: |

      §e/<command>§f - Show the current date and time in the server's time zone.
